### ISSUE TITLE
Add README please

### ISSUE THREAD

**Issue by rnowling** [janestreet/core_extended#11]
Can you add a README to the repo covering the basics of what Core_extended has that Core doesn't and the basics of building it? Thanks!

**Comment by agarwal** [comment]
Even better would be a website for the Core suite. A high level summary of all the libraries and how they fit together would go a long way to helping beginners get up and running.

**Comment by mars0i** [comment]
It would help simply to have at least a link to a current ocamldoc build.  The Base, Core_kernel, and Core github repos all have that now, which is very convenient.

**Comment by jsomers** [comment]
This no longer exists as a library per se. But the latest ocamldocs are here: https://ocaml.janestreet.com/ocaml-core/latest/doc/core_extended/index.html.
