### ISSUE TITLE
Switch to something like ocaml-re rather than re2

### ISSUE THREAD

**Issue by bluddy** [janestreet/core_extended#16]
Re2 is an external library, and is a more brittle dependency than just using an internal solution like [ocaml-re](https://github.com/ocaml/ocaml-re). For example, I'm having trouble getting the ocaml bindings to re2 to compile on OSX, which means I can't build core_extended, which means I can't build core_bench.

It also appears Re2 is used in only a few places in the code, so the transition should be easy.

**Comment by yminsky** [comment]
Seems good in principle, but not likely we'll get to it soon. A PR would be welcome!

**Comment by dwang20151005** [comment]
Looks like you got what you wanted: https://github.com/janestreet/core_extended/blob/master/core_extended.opam
