### ISSUE TITLE
Losing color in the output of Shell module

### ISSUE THREAD

**Issue by qwfy** [janestreet/core_extended#19]
I noticed that there is no reliable way to preserve the color in a command's output (like the coloring by `git diff`) in either `Core_extended.Shell.run_full` or `Core_extended.Shell.ssh_full`:

- if you set the [`verbose`](https://github.com/janestreet/core_extended/blob/913f9fb9f3adebbcca06c02416c14183ad8c2a71/src/shell.mli#L20) arg to `true`, then the color outputed by the command being run will be overwritten by [this line](https://github.com/janestreet/core_extended/blob/913f9fb9f3adebbcca06c02416c14183ad8c2a71/src/shell.ml#L142)

- if you set `verbose` to `false`, and use something like `print_endline` to print the output yourself, you lose the original color information, (even if `print_endline` preserves the color, sometimes you don't want to set `~verbose:false`, because the command being run might want to output a stream, like `tail -f`: you want to see the output as soon as it becomes available, not when the command exits)

Is this (when verbose, set color of stdout to green and error to red) a designed feature, or a bug?

**Comment by trefis** [comment]
Ping @aalekseyev .

**Comment by aalekseyev** [comment]
I think you're right about `verbose` being not great for this, but:

- It's not true that print_endline loses the original color information. The following works for me:

    print_string (Shell.run_full "ls" ["--color=always"]);;

- It's possible to print a stream like this:

    Shell.run_fold ~init:() ~f:(fun () output -> print_endline output; ((), `Continue)) "ls" ["--color=always"];;

- there are probably a bunch of ways of doing what you want without using `Shell` module:

    Core.Unix.fork_exec ~prog:"ls" ~argv:["ls"; "--color=always"] ();;

    Shexp_process.eval (Shexp_process.run "ls" ["--color=always"]);;

    Core_extended.Extended_unix.fork_exec "ls" ["--color=always"];;

Given the wide range of workarounds and the debug-like nature of `verbose` I don't think any change is warranted at this point.

**Comment by aalekseyev** [comment]
> Is this (when verbose, set color of stdout to green and error to red) a designed feature, or a bug?

Clearly someone thought it was a god idea when they wrote it and I can see this being useful when the underlying command doesn't prints colored text.

**Comment by aalekseyev** [comment]
Additional observation: `git diff` might be losing colors because it detects that the output is not a terminal. Some of the workarounds I proposed above also fix this.

I like wrapping such commands in a `socat` invocation (left as an exercise for the reader) though to simulate a terminal for them. :-)

**Comment by qwfy** [comment]
>  the debug-like nature of verbose ...

If `verbose` was designed to facilitate debugging, then it (good green, bad red) can be a good thing, makes one spot the error right away.

Didn't know about `git diff` detecting its output target :-)
