### ISSUE TITLE
Still does not compile on OpenBSD

### ISSUE THREAD

**Issue by krwesterback** [janestreet/core_extended#21]
The fix to issues #8/#10 did not enable successful compilation on OpenBSD as OpenBSD defines DEV_BSIZE in sys/param.h which is not #include'd, whereas FreeBSD must do it elsewhere if the fixes did enable successful compilation on FreeBSD. Unfortunately I don't have a FreeBSD box to test on.

I think modifying the code in extended_unix_stubs.c from

#if defined (__FreeBSD__) || defined (__OpenBSD__)
#include <ufs/ufs/quota.h>
#else
#include <sys/quota.h>
#endif

to something like

#if defined (__FreeBSD__)
#include <ufs/ufs/quota.h>
#elif defined (__OpenBSD__)
#include <sys/param.h>
#include <ufs/ufs/quota.h>
#else
#include <sys/quota.h>
#endif

should fix the issue.

I apologize for dropping the ball last time I passed through Ocaml via Real World Ocaml. I had not noticed the fix being committed after Anil showed me how to pin the package with my fix in place locally.

I am now working through RWO 2nd Ed Dev Edition and would be happy to test any fix.

**Comment by yminsky** [comment]
I think you should just avoid using Core_extended for now. In the next stable release (and in the current bleeding-edge release), Core_extended itself will be gone, with its constituent libraries broken out into smaller, standalone libraries. The main one used in RWO was the Shell library, which will be released as a standalone package.

That effectively resolves this issue, since there are no c-stubs in the Shell library, so this issue has to be gone for RWO.

**Comment by krwesterback** [comment]
[On Mon, Oct 01, 2018 at 04:54:00PM -0700, Yaron Minsky wrote:
> I think you should just avoid using Core_extended for now. In the next stable release (and in the current bleeding-edge release), Core_extended itself will be gone, with its constituent libraries broken out into smaller, standalone libraries. The main one used in RWO was the Shell library, which will be released as a standalone package.
> 
> That effectively resolves this issue, since there are no c-stubs in the Shell library, so this issue has to be gone for RWO.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/janestreet/core_extended/issues/21#issuecomment-426101317

Sounds good.  If I really need it I can resort to locally patching
again. Thanks for the quick reply.

.... Ken
