### ISSUE TITLE
Add madvise bindings

### ISSUE THREAD

**Issue by XVilka** [janestreet/core_extended#23]
To call the [madvise](https://linux.die.net/man/2/madvise) syscall for Linux, it is implemented in `Lwt_bytes` for example:

https://github.com/ocsigen/lwt/blob/master/src/unix/lwt_bytes.ml#L222

**Comment by jeremiedimino** [comment]
Internally, we already expose this call into a library that we call `mmap`. It exposes `mmap64`, `mremap`, `msync`, `mlock` and `munlock` and depends on Core. So it doesn't make sense for us to bind `madvise` in `core_extended`. We would publish our `mmap` library if there was demand for it.

In the meantime, I'm closing this issue.
