### ISSUE TITLE
openbsd quota patch no longer applies on latest core

### ISSUE THREAD

**Issue by avsm** [janestreet/core_extended#7]
From Kenneth Westerback:

```
This noticed the compiler change and recompiled everything, then
reported a few things that could be upgraded. 'opam upgrade' went
well right up to 54/60, and then failed on core_extended. :-(

#=== Error while installing core_extended.112.35.00 ===========================#
These patches didn't apply at /home/krw/.opam/system/build/core_extended.112.35.00:
 - openbsd-quota-disable.diff
```

**Comment by avsm** [comment]
Will take a look at this shortly -- am testing a large ocaml 4.02.3 upgrade here first http://recoil.org/~avsm/openbsd-patches/ocaml-4.02.3-3.patch.txt

**Comment by avsm** [comment]
I've fixed this in OPAM, but would it be possible to get this out of the opam-repository and into Core_extended's source code directly? It'll keep getting out of sync otherwise.

**Comment by diml** [comment]
Sure, I submitted the patch internally
