### ISSUE TITLE
rdtscp clobbers %rcx 

### ISSUE THREAD

**Issue by matildah** [janestreet/core_extended#9]
the \_\_asm__ stanza in the [rdtscp stub](https://github.com/janestreet/core_extended/blob/master/src/posix_clock_stubs.c#L58) should specify that %rcx is clobbered by the rdtscp instruction (see  [page 113](http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developers-manual.pdf) of Intel 64 and IA-32 Architectures
Software Developer’s Manual)

**Comment by diml** [comment]
Thanks, I submitted a feature for review internally

**Comment by diml** [comment]
Fixed by d333da7b49918e2bbb4c62bc20bd1566e25dc69f
